stages:
  - test

.test-shared: &test-shared
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - vendor/
  stage: test
  before_script:
    - /usr/local/bin/composer install --prefer-dist
    - cp tests/data/config-docker.php tests/data/config.php


test:5.6:
  <<: *test-shared
  image: yiisoftware/yii2-php:5.6-apache
  script:
    - php vendor/bin/phpunit -v --exclude caching,db,data


test:7.0:
  <<: *test-shared
  image: yiisoftware/yii2-php:7.0-apache
  script:
    - php vendor/bin/phpunit -v --exclude caching,db,data


test:7.1:
  <<: *test-shared
  image: yiisoftware/yii2-php:7.1-apache
  script:
    - php vendor/bin/phpunit -v --exclude caching,db,data
